package com.xdlv.weixing.bean;

import com.xdlv.weixing.bean.Dzlist;

public interface DzlistMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dzlist
	 * @mbggenerated
	 */
	int insert(Dzlist record);
}