package com.xdlv.weixing.bean;

import com.xdlv.weixing.bean.ImportDzRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ImportDzRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_dz_record
     *
     * @mbggenerated
     */
    int insert(ImportDzRecord record);

    List<ImportDzRecord> getAllImportDzRecords();

    ImportDzRecord getImportDzRecordByYearAndMonth(@Param("year")int year
            , @Param("month")int month);

    void updateImportDzRecordStatus(ImportDzRecord importDzRecord);

    List<ImportDzRecord> selectDzRecordByStatus(@Param("notification")String notification);

    List<ImportDzRecord> getLastedNotifyImportDzRecord();

}