package com.xdlv.weixing.bean;

import org.apache.ibatis.annotations.Param;
import com.xdlv.weixing.bean.UserValidate;

public interface UserValidateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_validate
	 * @mbggenerated
	 */
	int insert(UserValidate record);

	UserValidate[] selectUserValidateForNotSend();
	
	int updateStatusByPhone(@Param("phone")String phone,@Param("status")String status);
}