package com.xdlv.weixing.bean;

import com.xdlv.weixing.bean.UserCompany;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserCompanyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_company
	 * @mbggenerated
	 */
	int insert(UserCompany record);

	UserCompany getUserCompanyByPhone(String phone);

	int getUserCompanysCount();

    List<UserCompany> selectUserCompanys(@Param("start")int start, @Param("end")int end);
}