package com.xdlv.weixing.bean;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xdlv.weixing.bean.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int deleteUserByKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    User selectUserByKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

	User selectUserByName(@Param("name")String name);

	List<User> selectUsers(@Param("start")int start, @Param("limit")int limit);

	int selectUserCount();
}