package com.xdlv.weixing.bean;

import com.xdlv.weixing.bean.UserCompany;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserCompanyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_company
	 * @mbggenerated
	 */
	int insert(UserCompany record);

	UserCompany[] getUserCompanyByPhone(@Param("phone")String phone);

	int getUserCompanysCount(@Param("userCompany")UserCompany userCompany);

    List<UserCompany> selectUserCompanys(@Param("userCompany")UserCompany userCompany, @Param("start") int start, @Param("limit") int limit);

	int deleteForImport(UserCompany userCompany);

	List<UserCompany> selectUnBindUserCompany();

}