package com.xdlv.weixing.bean;

import com.xdlv.weixing.bean.Userdz;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserdzMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userdz
	 * @mbggenerated
	 */
	int deleteUserdzByKey(String phone);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userdz
	 * @mbggenerated
	 */
	int insert(Userdz record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userdz
	 * @mbggenerated
	 */
	Userdz selectUserdzByKey(String phone);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userdz
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Userdz record);

	List<Userdz> getAllUserdzs(@Param("start")int start, @Param("end")int end);

	Userdz selectUserdzByOpenid(@Param("openid")String openid);

	void deleteUserdzByOpenid(@Param("openid")String openid);
}